/* 
This statement creates the table, be sure to substitute the location in Amazon S3 where you store your exported EDR snapshots.

You need to specify a folder, not a specific object in S3 and all objects in this folder will be scanned by Athena when you run a query. 

Don't forget the trailing / at the end of the path, it will error without it! 

What we do here is create a table containing all the fields for all the data types to amke things simple, each data type will be exposed in it's own separate view
*/

CREATE EXTERNAL TABLE interceptx_edr.exported_snapshot (
         type STRING,
         pidStart STRING ,
         tidStart STRING ,
         time STRING ,
         name STRING ,
         accessEndTime STRING ,
         operationType STRING ,
         filePath STRING ,
         driveType STRING ,
         targetFilePath STRING ,
         targetDriveType STRING ,
         pid INT ,
         alertType STRING ,
         processPath STRING ,
         productId INT ,
         version STRING ,
         os STRING ,
         cpu STRING ,
         uid STRING ,
         computer STRING ,
         alertDetails STRING ,
         processName STRING ,
         processSha256 STRING ,
         loadTime STRING ,
         loadAddress STRING ,
         imageSize INT ,
         imagePath STRING ,
         fileSize INT ,
         sha1Hash STRING ,
         sha256Hash STRING ,
         startTime STRING ,
         endTime STRING ,
         connectionType STRING ,
         srcAddress STRING ,
         srcPort INT ,
         destAddress STRING ,
         destPort INT ,
         dataSent INT ,
         dataReceived INT ,
         dataRecieved INT ,
         stopTime STRING ,
         ppidStart STRING ,
         ptidStart STRING ,
         inheritPidStart STRING ,
         commandLine STRING ,
         windowsSessionId INT ,
         user STRING ,
         userSid STRING ,
         path STRING ,
         beaconType STRING ,
         threatName STRING ,
         processDriveType STRING ,
         fileDriveType STRING ,
         childProcessName STRING ,
         childProcessDriveType STRING ,
         childPid INT ,
         theadId INT ,
         operation STRING ,
         keyPath STRING ,
         valueName STRING ,
         url STRING ,
         data STRING ,
         startAddress STRING ,
         isRemote BOOLEAN ,
         iSSystem BOOLEAN ,
         windowsServiceId INT ,
         imageStartedIn STRING ,
         imageDriveType STRING ,
         authType STRING ,
         userName STRING ,
         domainName STRING ,
         logonType INT ,
         ipAddress STRING ,
         port INT ,
         reputation INT ,
         reputationSource STRING ,
         reputationExpiryTime STRING
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
         "ignore.malformed.json" = "true") LOCATION 's3://<<S3-BUCKET-NAME/S3-BUCKET-FOLDER/>>' ;
